// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:49efa1c2-c741-4a97-97b4-b98e4827caec",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_7oN59nnfK",
    "aws_user_pools_web_client_id": "3239f8h7l7qgtr6tsnqvh7b8mq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3hh7t4d35zg4nf2xksnb2uro7i.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "eu-west-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "eu-west-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
